version: 0.2

phases:
  pre_build:
    commands:
      ## ECRにログイン
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
 
      ## Dockerイメージのタグとして使用するため、Gitのコミットハッシュを取得
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      ## Dockerイメージのビルド
      - docker build -t kat_wiki_growi_app:$IMAGE_TAG .
      - docker build -t kat_wiki_growi_elasticsearch:$IMAGE_TAG ./elasticsearch
 
      ## DockerイメージのECRへのプッシュ
      - docker push kat_wiki_growi_app:$IMAGE_TAG
      - docker push kat_wiki_growi_elasticsearch:$IMAGE_TAG
 
      ## ECS+CodeDeployにどのイメージを使用するか指示するためのファイルを作成
      - printf '{"Version":"1.0","ImageURI":"%s","ImageURI2":"%s"}' kat_wiki_growi_app:$IMAGE_TAG kat_wiki_growi_elasticsearch:$IMAGE_TAG > imageDetail.json
 
artifacts:
  ## buildの最後で作成したファイルをアーティファクトとして流す
  files: imageDetail.json