version: '3'

services:
  app:
    image: 727498003651.dkr.ecr.ap-northeast-1.amazonaws.com/kat-wiki/app:latest
    ports:
      - 3000:3000    # localhost only by default
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/growi
      - ELASTICSEARCH_URI=http://127.0.0.1:9200/growi
      - PASSWORD_SEED=changeme
      # - FILE_UPLOAD=local     # activate this line if you use local storage of server rather than AWS
      # - MATHJAX=1             # activate this line if you want to use MathJax
      # - PLANTUML_URI=http://  # activate this line and specify if you use your own PlantUML server rather than public plantuml.com
      # - HACKMD_URI=http://    # activate this line and specify HackMD server URI which can be accessed from GROWI client browsers
      # - HACKMD_URI_FOR_SERVER=http://hackmd:3000  # activate this line and specify HackMD server URI which can be accessed from this server container

    command: "dockerize
              -wait tcp://127.0.0.1:27017
              -wait tcp://127.0.0.1:9200
              -timeout 60s
              npm run server:prod"
    volumes:
      - growi_data:/data

  mongo:
    image: mongo:3.6
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  elasticsearch:
    image: 727498003651.dkr.ecr.ap-northeast-1.amazonaws.com/kat-wiki/elasticsearch:latest
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # increase amount if you have enough memory
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  backup:
    image: weseek/mongodb-awesome-backup:0.2.0
    environment:
      - CRONMODE=true
      - CRON_EXPRESSION=0 4 * * *                               # change it
      # - AWS_ACCESS_KEY_ID=${Your IAM Access Key ID}           # change it
      # - AWS_SECRET_ACCESS_KEY=${Your IAM Secret Access Key}   # change it
      # - S3_TARGET_BUCKET_URL=s3://${Your Bucket Name}/        # change it
    restart: unless-stopped
    volumes:
      - ./crontab/root:/var/spool/cron/crontabs/root

volumes:
  growi_data:
  mongo_configdb:
  mongo_db:
  es_data:
